# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          dotnet-quality: preview

      - name: Version (release)
        run: |
          OLD=$(yq ".Project.PropertyGroup[0].Version" -p xml -o xml src/Pingmint.CodeGen.CSharp.CodeWriter/Pingmint.CodeGen.CSharp.CodeWriter.csproj)
          NEW="$OLD.${COUNTER}" yq ".Project.PropertyGroup[0].Version = env(NEW)" -p xml -o xml -i src/Pingmint.CodeGen.CSharp.CodeWriter/Pingmint.CodeGen.CSharp.CodeWriter.csproj
          cat src/Pingmint.CodeGen.CSharp.CodeWriter/Pingmint.CodeGen.CSharp.CodeWriter.csproj
        env:
          COUNTER: ${{ github.run_number }}
        if: github.ref == 'refs/heads/main'

      - name: Version (pre-release)
        run: |
          OLD=$(yq ".Project.PropertyGroup[0].Version" -p xml -o xml src/Pingmint.CodeGen.CSharp.CodeWriter/Pingmint.CodeGen.CSharp.CodeWriter.csproj)
          NEW="$OLD.${COUNTER}-alpha" yq ".Project.PropertyGroup[0].Version = env(NEW)" -p xml -o xml -i src/Pingmint.CodeGen.CSharp.CodeWriter/Pingmint.CodeGen.CSharp.CodeWriter.csproj
          cat src/Pingmint.CodeGen.CSharp.CodeWriter/Pingmint.CodeGen.CSharp.CodeWriter.csproj
        env:
          COUNTER: ${{ github.run_number }}
        if: github.ref != 'refs/heads/main'

      - name: Restore dependencies
        run: dotnet restore src/Pingmint.CodeGen.CSharp.CodeWriter

      - name: Build
        run: dotnet build --configuration Release --no-restore src/Pingmint.CodeGen.CSharp.CodeWriter

      - name: Test
        run: dotnet test --configuration Release --no-build --no-restore --verbosity normal src/Pingmint.CodeGen.CSharp.CodeWriter

      - name: Pack
        run: dotnet pack --configuration Release --no-build --no-restore --verbosity normal --output ./nupkg src/Pingmint.CodeGen.CSharp.CodeWriter

      - name: Push
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key $NUGET_API_KEY
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        if: github.ref == 'refs/heads/main'
